"""Add tracking_id to orders table

Revision ID: 1d862fbb1d56
Revises: 39b5509f9687
Create Date: 2025-09-19 14:58:09.676196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d862fbb1d56'
down_revision: Union[str, Sequence[str], None] = '39b5509f9687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_id')
    # ### end Alembic commands ###
