"""add created_at and updated_at to products

Revision ID: 39b5509f9687
Revises: b68325cdef93
Create Date: 2025-09-19 12:29:33.905029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b5509f9687'
down_revision: Union[str, Sequence[str], None] = 'b68325cdef93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 🟢 Step 1: Add new columns as nullable
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # 🟢 Step 2: Populate existing rows with a default value
    op.execute("UPDATE products SET created_at = NOW(), updated_at = NOW()")

    # 🟢 Step 3: Alter the columns to be non-nullable
    op.alter_column('products', 'created_at', nullable=False)
    op.alter_column('products', 'updated_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
