"""Add tracking_id to Order table

Revision ID: 3c48b07a79a8
Revises: 6f11a9e255ba
Create Date: 2025-09-21 16:07:56.259444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c48b07a79a8'
down_revision: Union[str, Sequence[str], None] = '6f11a9e255ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
