"""Add price column to order_items table

Revision ID: 6f11a9e255ba
Revises: 1d862fbb1d56
Create Date: 2025-09-21 14:38:40.371078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f11a9e255ba'
down_revision: Union[str, Sequence[str], None] = '1d862fbb1d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
