"""add selling_price and profit_margin to products

Revision ID: b68325cdef93
Revises: 8ae82742edf1
Create Date: 2025-09-19 12:12:57.642493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68325cdef93'
down_revision: Union[str, Sequence[str], None] = '8ae82742edf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the new columns as nullable
    op.add_column('products', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('profit_margin_percentage', sa.Float(), nullable=True))

    # Step 2: Set a default value for existing rows
    # Assuming a default profit margin of 25% for existing products
    op.execute("UPDATE products SET profit_margin_percentage = 25.0 WHERE profit_margin_percentage IS NULL")
    op.execute("UPDATE products SET selling_price = price * (1 + profit_margin_percentage / 100) WHERE selling_price IS NULL")
    
    # Step 3: Alter the columns to be non-nullable
    op.alter_column('products', 'selling_price', nullable=False)
    op.alter_column('products', 'profit_margin_percentage', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'profit_margin_percentage')
    op.drop_column('products', 'selling_price')
    # ### end Alembic commands ###